# Header
menu:
  Home: /home
  Historia y Estio: /Historia y Estio
  Los Aventureros Santa Cruz: /los-aventureros-santa-cruz
  Los Aventureros Samaipata: /los-aventureros-samaipata
  # Los Aventureros Concepcion: /Los Aventureros Concepcion
  Ofertas: /ofertas
  Contactos: /contactos
  Información Turística Santa Cruz: /informacion-turistica-santa-cruz
  Información Turistica Samaipata: /informacion-turistica-samaipata
  # Información Turística Concepcion: /Información Turística Concepcion
  # Archives: /archives
# rss: /atom.xml
    
# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: false
widgets:
# - category
# - tag
# - tagcloud
# - archive
# - recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics:
gauges_analytics:
favicon: /favicon.png
twitter: emialonzo
google_plus:
fb_admins:
fb_app_id:
